# Generated by Django 4.0.3 on 2022-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('desciption', models.TextField(max_length=200, null=True)),
                ('activitiy_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('desciption', models.TextField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('WEBDESIGN', 'COMPLETE'), ('CONTENT', 'PENDING'), ('SOCIAL', 'UNCOMPLETE')], default='WEBDESIGN', max_length=40)),
                ('client', models.ManyToManyField(to='cms.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('desciption', models.TextField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING'), ('UNCOMPLETE', 'UNCOMPLETE')], default='UNCOMPLETE', max_length=40)),
                ('duetade', models.DateTimeField()),
                ('project', models.ManyToManyField(to='cms.project')),
            ],
        ),
    ]
