# Generated by Django 4.0.3 on 2022-03-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='duetade',
            new_name='due_date',
        ),
    ]
