# Generated by Django 4.0.3 on 2022-03-29 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0003_employee_task_task_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_for',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
