# Generated by Django 4.0.3 on 2022-03-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_task_task_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
