# Generated by Django 4.0.3 on 2022-03-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_task_status_task_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='desciption',
            new_name='description',
        ),
    ]
