# Generated by Django 4.0.3 on 2022-03-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_desciption_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activitiy_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_for',
        ),
    ]
