# Generated by Django 4.0.3 on 2022-03-31 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0009_remove_activity_activitiy_date_remove_task_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_for',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
