# Generated by Django 4.0.3 on 2022-03-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_task_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='eduction',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('WEB DESIGNER', 'WEB DESIGNER'), ('CONTENT CONTENT_MANAGER', 'CONTENT MANAGER'), ('SOCIAL SOCIAL_MANAGER', 'SOCIAL_MANAGER')], default='WEB DESIGNER', max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='state_city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=40),
        ),
    ]
