# Generated by Django 4.0.3 on 2022-04-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_employee_address_employee_address2_employee_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(null=True),
        ),
    ]
