# Generated by Django 4.0.3 on 2022-04-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_task_due_task_due_date_task_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='happened',
            field=models.BooleanField(default=False),
        ),
    ]
