# Generated by Django 4.0.3 on 2022-04-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_activity_due_date_activity_happened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='happened',
            new_name='complete',
        ),
    ]
