# Generated by Django 4.0.3 on 2022-04-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_remove_client_email_remove_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
