# Generated by Django 4.0.3 on 2022-04-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_remove_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
