# Generated by Django 4.0.3 on 2022-04-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_employee_first_name_remove_employee_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='usermane',
            new_name='usernane',
        ),
    ]
