# Generated by Django 4.0.3 on 2022-04-05 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0020_rename_usermane_employee_usernane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='usernane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
