# Generated by Django 4.0.3 on 2022-04-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_employee_usernane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='usernane',
            new_name='username',
        ),
    ]
