# Generated by Django 4.0.3 on 2022-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
