# Generated by Django 4.0.3 on 2022-04-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_request_request_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
