# Generated by Django 4.0.3 on 2022-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
