# Generated by Django 4.0.3 on 2022-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_employeerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='employeerequest',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='requested_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
