# Generated by Django 4.0.3 on 2022-04-14 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0033_alter_employeerequest_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.employee'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
