# Generated by Django 4.0.4 on 2022-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('WEBDESIGN', 'COMPLETE'), ('CONTENT', 'PENDING'), ('SOCIAL', 'UNCOMPLETE')], default='WEBDESIGN', max_length=40),
        ),
    ]
