# Generated by Django 4.0.4 on 2022-04-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0037_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sentfrom+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=' Sentto+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Web design', 'Web design'), ('Content', 'Content'), ('Social media marketing', 'Social media marketing')], default='Web design', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('UNCOMPLETE', 'Uncomplete')], default='UNCOMPLETE', max_length=40),
        ),
    ]
