# Generated by Django 4.0.4 on 2022-04-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_employeerequest_is_resolved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='is_resolved',
        ),
    ]
