# Generated by Django 4.0.4 on 2022-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_remove_employeerequest_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
