# Generated by Django 4.0.4 on 2022-04-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_employeerequest_is_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='requested_at',
        ),
    ]
