# Generated by Django 4.0.4 on 2022-04-27 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_employeerequest_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 18, 35, 51, 448365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 18, 35, 51, 450539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Ucomplete', 'Uncomplete')], default='Ucomplete', max_length=40),
        ),
    ]
