# Generated by Django 4.0.4 on 2022-04-28 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_project_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 9, 38, 6, 450525, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 9, 38, 6, 447741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Uncomplete', 'Uncomplete')], default='Uncomplete', max_length=40),
        ),
    ]
