# Generated by Django 4.0.4 on 2022-05-02 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0045_alter_employeerequest_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autho+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 10, 28, 41, 407102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 10, 28, 41, 404651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee+', to=settings.AUTH_USER_MODEL),
        ),
    ]
